# permissions for end users to view mysqlrwhas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mysqlrwha-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mysql-operator
    app.kubernetes.io/part-of: mysql-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysqlrwha-viewer-role
rules:
- apiGroups:
  - mysql.github.com
  resources:
  - mysqlrwhas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mysql.github.com
  resources:
  - mysqlrwhas/status
  verbs:
  - get
