apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}-mycat
  namespace: {{.ObjectMeta.Namespace}}
  labels:
    app: {{.ObjectMeta.Name}}-mycat
spec:
  type: ClusterIP
  ports:
    - name: mycat
      port: 8066
      targetPort: 8066
  selector:
    app: {{.ObjectMeta.Name}}-mycat
